export const ENV = {
  // GitHub API Configuration
  GITHUB_API_BASE_URL: process.env.EXPO_PUBLIC_GITHUB_API_BASE_URL,
  GITHUB_TOKEN: process.env.EXPO_PUBLIC_GITHUB_TOKEN,
  GITHUB_REPO_OWNER: process.env.EXPO_PUBLIC_GITHUB_REPO_OWNER,
  GITHUB_REPO_NAME: process.env.EXPO_PUBLIC_GITHUB_REPO_NAME,
  
  // API URLs
  USERS_FILE_PATH: process.env.EXPO_PUBLIC_USERS_FILE_PATH,
  MENU_FILE_PATH: process.env.EXPO_PUBLIC_MENU_FILE_PATH,
  ORDERS_FILE_PATH: process.env.EXPO_PUBLIC_ORDERS_FILE_PATH,
  BANNERS_FILE_PATH: process.env.EXPO_PUBLIC_BANNERS_FILE_PATH,
  BOOKINGS_FILE_PATH: process.env.EXPO_PUBLIC_BOOKINGS_FILE_PATH,
  CART_FILE_PATH: process.env.EXPO_PUBLIC_CART_FILE_PATH,
  DINE_FILE_PATH: process.env.EXPO_PUBLIC_DINE_FILE_PATH,
  
  // OpenRouteService API Key
  OPENROUTE_API_KEY: process.env.EXPO_PUBLIC_OPENROUTE_API_KEY,
};

export const OPENROUTE_API_KEY = ENV.OPENROUTE_API_KEY || '';
